"""Adding column task

Revision ID: 8f2c9fae81f8
Revises: 
Create Date: 2021-05-26 12:01:27.719713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2c9fae81f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserData',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email_id', sa.String(length=100), nullable=False),
    sa.Column('phn_number', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('task',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('taskname', sa.String(length=100), nullable=True),
    sa.Column('taskpriority', sa.Integer(), nullable=True),
    sa.Column('taskdescription', sa.String(length=100), nullable=True),
    sa.Column('taskcreator_id', sa.String(length=100), nullable=True),
    sa.Column('taskstatus', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['taskcreator_id'], ['UserData.email_id'], ),
    sa.PrimaryKeyConstraint('taskid'),
    sa.UniqueConstraint('taskid')
    )
    op.drop_table('user_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phn_number', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('email_id')
    )
    op.drop_table('task')
    op.drop_table('UserData')
    # ### end Alembic commands ###
